//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expenses
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceType
    {
        public int InsuranceTypeId { get; set; }
        public int InsuranceId { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<decimal> Premium { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
    
        public virtual Insurance Insurance { get; set; }
    }
}
