//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expenses
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintenance
    {
        public Maintenance()
        {
            this.MaintenanceHistories = new HashSet<MaintenanceHistory>();
        }
    
        public int MaintenanceId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<MaintenanceHistory> MaintenanceHistories { get; set; }
    }
}
