//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expenses
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceHistory
    {
        public int TypeId { get; set; }
        public int MaintenanceId { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Provider { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> DateDone { get; set; }
    
        public virtual Maintenance Maintenance { get; set; }
    }
}
