//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expenses
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceType
    {
        public int ResourceTypeId { get; set; }
        public int ResourceId { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string Bank { get; set; }
        public string PaymentMethod { get; set; }
    
        public virtual Resource Resource { get; set; }
    }
}
