//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expenses
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        public Resource()
        {
            this.ResourceTypes = new HashSet<ResourceType>();
        }
    
        public int ResourceId { get; set; }
        public string ResourceTypeDescription { get; set; }
    
        public virtual ICollection<ResourceType> ResourceTypes { get; set; }
    }
}
